### ISSUE TITLE
업로드 후 수정 관련

### ISSUE THREAD

**Issue by Heekng** [jojoldu/markdown-tistory#21]
write 후 카테고리, 태그, 공개발행 후 저장하였을 때, 인용구가 style1로 변경되는 문제가 있습니다.
따로 매뉴얼이 없어보여 가이드가 가능하다면 요청드립니다.

**Comment by jojoldu** [comment]
@Heekng 앗? 수정기능을 최근에 써본적이 없었는데 아마 티스토리가 기본 style을 1과 2를 형태를 변경해서 그런것 같습니다.
이건 강제로 style2를 기본으로 가져가도록 코드수정하겠습니다.

**Comment by Heekng** [comment]
빠른 답변 감사드립니다.
혹시 수정기능을 사용하시지 않았다면 카테고리나 태그는 어떻게 사용하셨나요?
