### ISSUE TITLE
대표 이미지 추가 방법

### ISSUE THREAD

**Issue by songyouhyun** [jojoldu/markdown-tistory#30]
안녕하세요.
`markdown-tistory`를 사용해서 포스팅을 진행하는 와중에 궁금한 게 생겨 이슈로 남깁니다.
## 1번
현재 명령어를 통해 **글의 내용에 노출되지 않는 대표 이미지 설정하는 방법**을 모르겠습니다.
때문에 tistory에서 직접 `글 수정` -> `완료 버튼 클릭` -> `대표 이미지 설정` -> `발행` 과정을 거치고 있는데요.

하지만 tistory에서 직접 글 수정을 진행하게 되면 정상적으로 들여쓰기가 적용된 코드문이 다음과 같이 평문으로 출력되게 됩니다.

```java
public enum ExampleEnum {     APPLE('apple'),     BANNA('banana'),      private String value;      public ExampleEnum(String value) {      this.value = value;     }     ... }
```
글을 직접 수정할 때 서식이 `기본 모드`로 변경되기 때문이라고 추측하고 있습니다.
때문에 tistory에서 직접 글 수정을 진행하고 싶지 않습니다.

write command를 통해 글을 포스팅할 때, 글의 내용에는 노출되지 않는 대표 이미지를 설정하는 방법이 있나요?

## 2번
1번의 과정을 거치고 update command를 통해 정상적으로 들여쓰기가 적용된 글로 수정할 수 있습니다.
하지만 해당 명령어를 통해 글 수정시, 대표 이미지가 초기화됩니다.

update command를 통해 글을 수정하더라도 대표 이미지가 초기화되지 않는 방법이 있나요?

**Comment by eodn** [comment]
저도 같은 내용이 궁금합니다.
