### ISSUE TITLE
Bug : 이미지 업로드 

### ISSUE THREAD

**Issue by jhleed** [jojoldu/markdown-tistory#7]
마크다운 이미지 문법에서 Alt text 부분이 누락되면 이미지가 올라가지 않는 현상을 발견하였습니다. 
(notion에서 기본 markdown export를 하면 alt text가 변경되는 형태라서 현재 수동으로 바꿔주고 있습니다. ㅎㅎ)

`![Alt text](/path/to/img.jpg)`  => Alt text가 누락되는 경우 이미지가 올라가지 않음

이미지가 올라가지 않는 경우
![image](https://user-images.githubusercontent.com/13193624/48873944-fb338300-ee33-11e8-97e5-488e5f45b96f.png)

이미지가 정상적으로 올라가는 경우
![image](https://user-images.githubusercontent.com/13193624/48873917-d93a0080-ee33-11e8-9c8d-1189d649d9af.png)

**Comment by jojoldu** [comment]
앗 notion에서 변경하면 그렇게 되는군요!
저는 직접 마크다운을 작성하다보니 alt를 넣고 있었는데, 없을 경우 파일명을 default로 하도록 변경해야겠습니다.
제보 감사합니다 :)

**Comment by jojoldu** [comment]
@jhleed 안녕하세요 종호님 :)
0.1.5 버전 업데이트로 해당 문제 해결되었습니다
패키지 업데이트 해보시면 확인 가능하세요 :)

**Comment by jhleed** [comment]
@jojoldu 앗, 벌써 업데이트가 되었네요! 빠른 해결 감사드립니다. ^^
