### ISSUE TITLE
티스토리 Desktop 버전에서 <code> 스타일이 적용되지 않는 현상

### ISSUE THREAD

**Issue by jhleed** [jojoldu/markdown-tistory#8]
안녕하세요! 
markdown-tistory를 너무 사랑하는 유저입니다.

티스토리에 업로드를 하는데 아래와 같은 현상을 발견해서 이슈 등록하였습니다.

**현상**
markdown 문법 중 코드 블록(```)을 사용하여 코드를 쓰면, 모바일에서는 스타일이 적용이 잘 되는데, 데스크탑 버전에서는 코드 블록의 스타일이 적용되지 않았습니다.

샘플 : https://jhleed.tistory.com/124
_~~(아직 다듬은 글이 아닌데, 샘플을 보여드려야 해서 공개로 바꿨네요 ㅋㅋ)~~_

**모바일 버전**
![image](https://user-images.githubusercontent.com/13193624/51718709-de146e00-2089-11e9-926e-e3419da19186.png)

**데스크탑 버전**
![image](https://user-images.githubusercontent.com/13193624/51718696-d48b0600-2089-11e9-8456-d49bcbebdf15.png)

현재까지 파악한 내용은 **모바일에서는 `<pre>` 태그에 `hljs, lua` 클래스가 적용이 되었는데 데스크탑에서는 적용이 되어 있지 않습니다.** 아마도 이와 관련이 있을 듯 합니다.

![image](https://user-images.githubusercontent.com/13193624/51718757-161bb100-208a-11e9-9735-19bb238f843c.png)

![image](https://user-images.githubusercontent.com/13193624/51718791-33507f80-208a-11e9-86f3-7e330e1c8028.png)

유용한 플러그인 만들어주시고, 업데이트도 잘 해주셔서 항상 감사하게 생각하고 있습니다. 
좋은 하루 되세요. :)

**Comment by jojoldu** [comment]
@jhleed 앗 종호님 제보 감사합니다!
음 방금 제 PC로 테스트를 했는데,
현재 제 PC에서는 정상적으로 css가 적용됩니다.

![image](https://user-images.githubusercontent.com/7760496/51747614-5f511c80-20ed-11e9-8a1a-7b4dfcba9230.png)

혹시 블로그에 사용하고 계신 하이라이트.js가 어떤거 쓰시나요?
하이라이트 js의 문제가 아닐까 싶습니다.

markdown -> html로 전환하는 npm 패키지를 변경없이 반영해놓은 상태라서요.

**Comment by jojoldu** [comment]
@jhleed 오! 넵넵 ㅋㅋ 그럼 이이슈는 클로즈 하겠습니다! :)
